name: Core
main: Kad\Core\Core
api: 3.11.1
version: 3.0.0
load: POSTWORLD
author: KadTheHunter
commands:
  gmc:
    description: Changes your gamemode to Creative
    permission: core.gmc.use
  gms:
    description: Changes your gamemode to Survival
    permission: core.gms.use
  gma:
    description: Changes your gamemode to Adventure
    permission: core.gma.use
  gmspc:
    description: Changes your gamemode to Spectator
    permission: core.gmspc.use
  day:
    description: Changes the time to Day in the world your in
    permission: core.day.use
  night:
    description: Changes the time to Night in the world you're in
    permission: core.night.use
  clearinv:
    description: Clears you're Inventory
    aliases: ["invclear"]
  hub:
    description: Teleports you to the Hub
    aliases: ["lobby","spawn"]
  rules:
    description: Shows the servers Rules
  nv:
    description: Gives you Night Vision

permissions:
  core.gmc.use:
    description: GMC Command
    default: OP
  core.gms.use:
    description: GMS Command
    default: OP
  core.gma.use:
    description: GMA Command
    default: OP
  core.gmspc.use:
    description: GMSPC Command
    default: OP
  core.day.use:
    description: DAY Command
    default: OP
  core.night.use:
    description: NIGHT Command
    default: OP
  core.worldsign.use:
    description: Allows usage of [WORLD] Signs
    default: OP
